<a href="https://colab.research.google.com/github/s61711299-sketch/MSSP6070/blob/main/PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import pandas as pd

In [5]:
GITHUB_USERNAME="s61711299-sketch"
REPO_NAME="MSSP6070"
TOKEN="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"
FOLDER_NAME="week05"
CSV_FILES=["aapl.csv","amzn.csv","fb.csv","goog.csv","nflx.csv"]

repo_url=f"https://{TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"
if os.path.exists(REPO_NAME):
    !rm -rf {REPO_NAME}
print("Clone")
!git clone {repo_url}
target_dir=os.path.join(REPO_NAME, FOLDER_NAME)
os.chdir(target_dir)
dfs={}
for file in CSV_FILES:
    if os.path.exists(file):
        dfs[file]=pd.read_csv(file)
        print(f"success {file}|{dfs[file].shape}")
    else:
        print(f"can not find{file}")

Clone
Cloning into 'MSSP6070'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 106 (delta 41), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (106/106), 1.74 MiB | 8.19 MiB/s, done.
Resolving deltas: 100% (41/41), done.
success aapl.csv|(251, 6)
success amzn.csv|(251, 6)
success fb.csv|(251, 6)
success goog.csv|(251, 6)
success nflx.csv|(251, 6)

In [7]:
dfs_with_ticker=[]
for file in CSV_FILES:
    df=pd.read_csv(file)
    ticker_symbol=file.replace('.csv','').upper()
    df['ticker']=ticker_symbol
    dfs_with_ticker.append(df) #add column ticker

In [10]:
all_stocks=pd.concat(dfs_with_ticker,ignore_index=True)
all_stocks.to_csv('faanf.csv',index=False)
df_fannf=pd.read_csv('faanf.csv')
df_fannf['date']=pd.to_datetime(df_fannf['date'])
df_fannf['volume']=df_fannf['volume'].astype(int)
df_fannf_sorted=df_fannf.sort_values(by=['date','ticker'])

In [14]:
top7volume=df_fannf_sorted.nlargest(7,'volume')
print("Highest 7 volume：")
display(top7volume)

Highest 7 volume：

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [17]:
melted_df=pd.melt(df_fannf,
    id_vars=['date','ticker'],
    var_name='metric',
    value_name='value')
print("melted data：")
display(melted_df.head())

melted data：

        date ticker metric     value
0 2018-01-02   AAPL   open  166.9271
1 2018-01-03   AAPL   open  169.2521
2 2018-01-04   AAPL   open  169.2619
3 2018-01-05   AAPL   open  170.1448
4 2018-01-08   AAPL   open  171.0375